DROP TABLE IF EXISTS CHARACTER_TB;
DROP TABLE IF EXISTS PHRASE_TB;

CREATE TABLE CHARACTER_TB (
  id VARCHAR(250) IDENTITY PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  picture VARCHAR(250) NOT NULL,
  age DOUBLE NOT NULL
);
CREATE TABLE PHRASE_TB (
  id VARCHAR(250) IDENTITY PRIMARY KEY,
  character VARCHAR(250) NOT NULL,
  phrase VARCHAR(250) NOT NULL
);

